name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'testdata/**'
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'testdata/**'
      - '*.md'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Test
        run: cargo nextest run --no-fail-fast
